FROM ubuntu:19.04

COPY ./build/bin /app
COPY ./config/fdb.cluster /app/fdb.cluster
COPY ./config/clients.deb /tmp/fdb.deb
RUN dpkg -i /tmp/fdb.deb

ENTRYPOINT /bin/bash -c "/app/fdbdoc -C /app/fdb.cluster -V -l 0.0.0.0:27016 -nl 0.0.0.0:8081"
